import {createReaction,randomDelay} from '../games/reaction/logic.js';
import {encodeTarget,decodeTarget,compareTarget} from './model.js';
import {shareText} from '../core/share.js';
import {i18n,t} from '../i18n/index.js';
import {track} from '../core/analytics.js';
export function mount(root){let target=null,invalid=false,score=null,link='',attempt=createReaction(),timer,frame,dead=false;const get=name=>root.querySelector(`[data-duel-${name}]`),button=get('action'),listeners=[];const listen=(node,event,fn)=>{node.addEventListener(event,fn);listeners.push(()=>node.removeEventListener(event,fn));};
 if(root.dataset.duelMode==='play')try{const params=new URLSearchParams(location.search);if(params.getAll('id').length!==1)throw new Error();target=decodeTarget(params.get('id'));track('duel_opened',{game_id:'reaction',mode:'duel'});}catch{invalid=true;}
 function setStatus(key){const status=get('status');if(key){status.dataset.i18n=key;status.textContent=t(key);}else{delete status.dataset.i18n;status.textContent='';}}
 function render(){button.dataset.state=attempt.state;button.textContent=t(`reaction.${attempt.state}`);button.hidden=invalid||score!==null;get('target').textContent=target!==null?t('duel.target',{score:target}):'';get('result').textContent=invalid?t('duel.invalid'):score!==null?`${target!==null?t('duel.'+compareTarget(score,target))+' · ':''}${score} ms`:['early','interrupted'].includes(attempt.state)?t(`reaction.${attempt.state}`):'';get('share').hidden=!link;get('link-label').hidden=!link;get('link').value=link;get('rematch').hidden=score===null;}
 function clear(){clearTimeout(timer);cancelAnimationFrame(frame);}
 const interrupt=()=>{if(attempt.interrupt()){clear();render();}};
 function activate(event){if(event?.repeat||dead||invalid||score!==null||document.hidden||!document.hasFocus())return;if(['ready','early','interrupted'].includes(attempt.state)){attempt.start();render();timer=setTimeout(()=>{frame=requestAnimationFrame(()=>{if(!dead&&!document.hidden&&document.hasFocus()&&attempt.signal())render();});},randomDelay());}else{const result=attempt.tap();clear();if(result&&!result.early){score=Math.round(result.actualMs);link='https://katovia.com/d/?id='+encodeURIComponent(encodeTarget(score));track('duel_completed',{game_id:'reaction',mode:'duel',score_bucket:Math.floor(score/100)});track('duel_created',{game_id:'reaction',mode:'duel'});}render();}}
 listen(button,'pointerdown',event=>{if(event.button!==0||event.isPrimary===false)return;event.preventDefault();button.focus({preventScroll:true});activate();});listen(button,'keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();activate(event);}});listen(button,'click',event=>{if(!event.detail)activate();});listen(window,'blur',interrupt);listen(document,'visibilitychange',()=>{if(document.hidden)interrupt();});
 listen(get('rematch'),'click',()=>{clear();score=null;link='';attempt=createReaction();setStatus(null);render();button.focus();track('rematch_clicked',{game_id:'reaction'});});
 listen(get('share'),'click',async()=>{if(!link)return;const result=await shareText({title:'Katovia Reaction Duel',text:t('duel.target',{score}),url:link});if(dead)return;if(result.status==='manual'){get('link').focus();get('link').select();}setStatus(result.status==='cancelled'?'creator.cancelled':result.status==='manual'?'tool.manual':result.status==='copied'?'tool.copied':'creator.handoff');});
 const unsubscribe=i18n.subscribe(render);render();root.dataset.ready='true';return {dispose(){dead=true;clear();unsubscribe();listeners.forEach(fn=>fn());}};
}
