import {test,expect} from '@playwright/test';
test('Creator works with denied storage, locale preserves user text and malformed links fail safely',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('denied');}}));await page.goto('/create/');await expect(page.locator('[data-creator]')).toHaveAttribute('data-ready','true');await page.locator('[data-creator-title]').fill('Benim quizim');await page.locator('[data-question]').fill('Çay mı?');await page.locator('[data-option]').nth(0).fill('Evet');await page.locator('[data-option]').nth(1).fill('Hayır');await expect(page.locator('[data-creator-status]')).toContainText('could not be saved');await page.locator('[data-locale="tr"]').click();await expect(page.locator('[data-question]')).toHaveValue('Çay mı?');await page.locator('[data-creator-publish]').click();expect(await page.locator('[data-creator-link]').inputValue()).toContain('/p/#');await page.goto('/p/#bad');await page.locator('[data-locale="tr"]').click();await expect(page.locator('[data-creation-status]')).toContainText('geçersiz');
});
test('Creator draft, safe preview, shared link, friend result and create-own journey',async({page,context},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/create/');const root=page.locator('[data-creator]');await expect(root).toHaveAttribute('data-ready','true');await page.locator('[data-creator-title]').fill('My <img src=x onerror=alert(1)> quiz');await page.locator('[data-question]').fill('Tea or coffee?');await page.locator('[data-option]').nth(0).fill('Tea');await page.locator('[data-option]').nth(1).fill('Coffee');await page.locator('[data-creator-preview]').click();await expect(page.locator('[data-creator-player] h2')).toContainText('<img');expect(await page.locator('[data-creator-player] img').count()).toBe(0);await page.locator('[data-answer="0"]').click();await expect(page.locator('[data-quiz-result]')).toHaveText('1 / 1');await page.locator('[data-creator-publish]').click();const link=await page.locator('[data-creator-link]').inputValue();expect(link).toMatch(/^https:\/\/katovia.com\/p\/#/);expect(link.length).toBeLessThan(1900);await page.reload();await expect(page.locator('[data-creator-title]')).toHaveValue('My <img src=x onerror=alert(1)> quiz');
 const friend=await context.newPage();await friend.goto(link.replace('https://katovia.com','http://127.0.0.1:4173'));await expect(friend.locator('[data-creation]')).toHaveAttribute('data-ready','true');await friend.locator('[data-answer="0"]').click();await expect(friend.locator('[data-quiz-result]')).toHaveText('1 / 1');await friend.locator('[data-creator-player] a').click();await expect(friend).toHaveURL(/\/create\/$/);await friend.close();
 for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('creator-mobile.png'),fullPage:true});expect(errors).toEqual([]);
});
