import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {shareProject} from '../../src/language-forge/project/codec.js';
import {patchProject} from '../../src/language-forge/project/model.js';
const route='/create/language-forge/',key='katovia:language-forge:active',seed='0123456789abcdef0123456789abcdef';
async function setup(page){await page.addInitScript(seed=>{Object.defineProperty(crypto,'getRandomValues',{value:array=>{for(let i=0;i<array.length;i++)array[i]=parseInt(seed.slice(i*2,i*2+2),16);return array;}});Object.defineProperty(navigator,'share',{value:undefined,configurable:true});Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedForgeLink=text;}},configurable:true});},seed);await page.goto(route);await expect(page.locator('[data-forge]')).toHaveAttribute('data-ready','true');}
async function generate(page){await page.locator('[data-forge-submit]').click();await expect(page.locator('[data-forge-result]')).toBeVisible();}
const project=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)).value,key);
async function edit(page,id,value){const row=page.locator(`[data-forge-entry="${id}"]`);await row.locator('summary').click();await row.locator('[data-forge-word-action=edit]').click();await row.locator('input').fill(value);await row.locator('[data-forge-edit-apply]').click();}
test('rename/edit advisory override, hard collisions, reroll isolation and grammar-only preservation',async({page})=>{
 await setup(page);await generate(page);const original=await page.locator('[data-forge-entry] dd').allTextContents();
 await page.locator('[data-forge-rename]').click();await page.locator('[data-forge-name-editor] input').fill('Şafak');await page.locator('[data-forge-name-editor] [data-forge-edit-apply]').click();await expect(page.locator('[data-forge-name-editor]')).toContainText('does not fully match');await page.locator('[data-forge-name-editor] [data-forge-edit-apply]').click();await expect(page.locator('[data-forge-name]')).toHaveText('Şafak');
 await edit(page,'noun.water','malori');await expect(page.locator('[data-forge-sentence="sentence.drink-water"] .forge-surface')).toContainText('malori');
 await edit(page,'noun.water','rima');await expect(page.locator('[data-forge-editor]')).toContainText('Another concept');await expect(page.locator('[data-forge-entry="noun.water"] dd')).toHaveText('malori');await page.locator('[data-forge-edit-cancel]').click();
 const p=await project(page);expect(p.edits.languageName).toBe('Şafak');expect(p.edits.words[0].value).toBe('malori');
 await edit(page,'noun.water','rimo');await expect(page.locator('[data-forge-editor]')).toContainText('grammar marker');await page.locator('[data-forge-edit-cancel]').click();
 await edit(page,'noun.water','xava');await expect(page.locator('[data-forge-editor]')).toContainText('does not fully match');await page.locator('[data-forge-edit-apply]').click();await expect(page.locator('[data-forge-entry="noun.water"] dd')).toHaveText('xava');
 const before=await page.locator('[data-forge-entry] dd').allTextContents();const row=page.locator('[data-forge-entry="noun.fire"]');await row.locator('summary').click();await row.locator('[data-forge-word-action=reroll]').click();const after=await page.locator('[data-forge-entry] dd').allTextContents();expect(after.filter((x,i)=>x!==before[i])).toHaveLength(1);await expect(page.locator('[data-forge-name]')).toHaveText('Şafak');
 await page.locator('[data-forge-change]').click();await page.locator('.forge-advanced summary').click();await page.locator('[data-forge-order]').selectOption('SOV');await generate(page);expect(await page.locator('[data-forge-entry] dd').allTextContents()).toEqual(after);await expect(page.locator('[data-forge-name]')).toHaveText('Şafak');expect(original).not.toEqual(after);
});
test('save/restore, start-over cancel/confirm preserves unrelated storage, sound change confirmation',async({page})=>{
 await setup(page);await page.evaluate(()=>localStorage.setItem('unrelated','keep'));await generate(page);const before=await project(page);await page.reload();await expect(page.locator('[data-forge-restore]')).toBeVisible();await page.locator('[data-forge-resume]').click();expect(await project(page)).toEqual(before);
 await page.locator('[data-forge-change]').click();await page.locator('input[value=crisp]').check();await page.locator('[data-forge-submit]').click();await expect(page.locator('[data-forge-confirm]')).toContainText('word edits will not carry');await page.locator('[data-forge-confirm-no]').click();expect(await project(page)).toEqual(before);await page.locator('[data-forge-submit]').click();await page.locator('[data-forge-confirm-yes]').click();await expect(page.locator('[data-forge-summary]')).toContainText('CRISP');
 await page.locator('[data-forge-new]').click();await page.locator('[data-forge-confirm-no]').click();await expect(page.locator('[data-forge-result]')).toBeVisible();await page.locator('[data-forge-new]').click();await page.locator('[data-forge-confirm-yes]').click();expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBeNull();expect(await page.evaluate(()=>localStorage.getItem('unrelated'))).toBe('keep');
});
test('JSON export/download/import roundtrip, safe replacements and malformed/oversized files',async({page})=>{
 await setup(page);await generate(page);const before=await project(page);const downloading=page.waitForEvent('download');await page.locator('[data-forge-export]').click();const download=await downloading;expect(download.suggestedFilename()).toBe('language-forge.json');expect(JSON.parse(await readFile(await download.path(),'utf8'))).toEqual(before);
 await page.locator('[data-forge-file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await expect(page.locator('[data-forge-status]')).toContainText('invalid');expect(await project(page)).toEqual(before);
 await page.locator('[data-forge-file]').setInputFiles({name:'big.json',mimeType:'application/json',buffer:Buffer.alloc(16385)});await expect(page.locator('[data-forge-status]')).toContainText('16 KiB');expect(await project(page)).toEqual(before);
 const renamed={...before,edits:{...before.edits,languageName:'New Realm'}};await page.locator('[data-forge-file]').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(renamed))});await expect(page.locator('[data-forge-confirm]')).toBeVisible();expect(await project(page)).toEqual(before);await page.locator('[data-forge-confirm-yes]').click();await expect(page.locator('[data-forge-name]')).toHaveText('New Realm');
});
test('share snapshots/receiver readonly/copy protect existing project and preserve locale/hash',async({page,browser})=>{
 await setup(page);await generate(page);await page.locator('[data-forge-share]').click();await expect(page.locator('[data-forge-status]')).toHaveText('Link copied.');const link=await page.evaluate(()=>window.copiedForgeLink);const source=await project(page);expect(link.length).toBeLessThanOrEqual(1900);expect(link).toBe(shareProject(source).url);
 const local=patchProject(source,{semanticId:'noun.water',value:'malori'});const localRaw=JSON.stringify({version:1,value:local});await page.evaluate(({key,localRaw})=>localStorage.setItem(key,localRaw),{key,localRaw});
 await page.goto(link.replace('https://katovia.com','http://127.0.0.1:4173'));await expect(page.locator('[data-forge-receiver]')).toBeVisible();await expect(page.locator('[data-forge-rename]')).not.toBeVisible();await expect(page.locator('[data-forge-word-action]')).toHaveCount(0);expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(localRaw);
 const fragment=new URL(page.url()).hash;await page.locator('.forge-result-nav a[href="#forge-dictionary"]').click();expect(new URL(page.url()).hash).toBe(fragment);await expect(page.locator('[data-forge-result]')).toBeVisible();await page.locator('[data-locale="tr"]').click();expect(new URL(page.url()).hash).toBe(fragment);await expect(page.locator('[data-forge-name]')).toHaveText('Neniru');
 await page.locator('[data-forge-copy-project]').click();await expect(page.locator('[data-forge-confirm]')).toBeVisible();expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(localRaw);await page.locator('[data-forge-confirm-yes]').click();expect(new URL(page.url()).hash).toBe('');await expect(page.locator('[data-forge-rename]')).toBeVisible();expect((await project(page)).edits.words).toHaveLength(0);
 await edit(page,'noun.water','malori');const context=await browser.newContext();const receiver=await context.newPage();await receiver.goto(link.replace('https://katovia.com','http://127.0.0.1:4173'));await expect(receiver.locator('[data-forge-entry="noun.water"] dd')).toHaveText('nera');expect(await receiver.evaluate(key=>localStorage.getItem(key),key)).toBeNull();await context.close();
});
test('URL budget blocks share without dropping edits; receiver rejects malformed/unknown payloads',async({page})=>{
 await setup(page);await generate(page);const p=await project(page);p.edits.words=(await page.locator('[data-forge-entry]').evaluateAll(nodes=>nodes.map(n=>n.dataset.forgeEntry))).map((semanticId,i)=>({semanticId,value:'z'+String.fromCharCode(97+Math.floor(i/26))+String.fromCharCode(97+i%26)+'a'.repeat(21),source:'manual',rerollCounter:0}));
 await page.locator('[data-forge-file]').setInputFiles({name:'custom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await page.locator('[data-forge-confirm-yes]').click();await expect(page.locator('[data-forge-share-budget]')).toContainText('too customized');await page.locator('[data-forge-share]').click();await expect(page.locator('[data-forge-status]')).toContainText('too customized');expect((await project(page)).edits.words).toHaveLength(64);await expect(page.locator('[data-forge-export]')).toBeEnabled();
 for(const fragment of ['#lf1.bad%','#lf2.abc']){await page.goto(route+fragment);await expect(page.locator('[data-forge-invalid]')).toBeVisible();await expect(page.locator('[data-forge-result]')).not.toBeVisible();await expect(page.locator('[data-forge-form]')).not.toBeVisible();}
});
test('suffix edit updates decomposition; unavailable storage stays usable; mobile actions and no external network',async({page},info)=>{
 const external=[],errors=[];page.on('request',r=>{if(new URL(r.url()).hostname!=='127.0.0.1')external.push(r.url());});page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('denied');}}));await setup(page);await page.locator('input[value=crisp]').check();await generate(page);await expect(page.locator('[data-forge-storage-warning]')).toBeVisible();await edit(page,'noun.child','kapoti');await expect(page.locator('[data-forge-sentence="sentence.children-moon"] .forge-surface')).toContainText('kapoti');
 await page.locator('[data-forge-explanation="sentence.children-moon"] summary').click();await expect(page.locator('[data-forge-explanation="sentence.children-moon"]')).toContainText('kapoti → child');
 for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('forge-phase4-mobile.png'),fullPage:true});await edit(page,'noun.child','xava');await page.locator('[data-locale="tr"]').click();await expect(page.locator('[data-forge-editor] input')).toHaveValue('xava');await page.locator('[data-forge-editor]').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('forge-edit-mobile.png')});expect(external).toEqual([]);expect(errors).toEqual([]);
});
test('receiver hash navigation protects the in-memory local project even when storage is denied',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('denied');}}));await setup(page);await generate(page);const original=await page.locator('[data-forge-entry] dd').allTextContents();
 await page.locator('[data-forge-share]').click();const link=await page.evaluate(()=>window.copiedForgeLink);await page.evaluate(fragment=>{location.hash=fragment;},new URL(link).hash);await expect(page.locator('[data-forge-receiver]')).toBeVisible();
 await page.locator('[data-forge-copy-project]').click();await expect(page.locator('[data-forge-confirm]')).toBeVisible();await page.locator('[data-forge-confirm-no]').click();await page.evaluate(()=>{location.hash='';});await expect(page.locator('[data-forge-rename]')).toBeVisible();expect(await page.locator('[data-forge-entry] dd').allTextContents()).toEqual(original);
});
