import {test,expect} from '@playwright/test';
test('five tools produce real outputs, invalid JSON and slow regex recover without blocking',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const visit=async id=>{await page.goto('/tools/'+id+'/');await expect(page.locator('[data-tool]')).toHaveAttribute('data-ready','true');for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}};
 await visit('json-formatter');await page.locator('[data-tool-input]').fill('{"a":1}');await page.locator('[data-tool-run]').click();await expect(page.locator('[data-tool-output]')).toHaveValue('{\n  "a": 1\n}');await page.locator('[data-tool-input]').fill('{bad}');await page.locator('[data-tool-run]').click();await expect(page.locator('[data-tool-output]')).toHaveValue('');
 await visit('text-diff');await page.locator('[data-tool-input]').fill('a\nb');await page.locator('[data-tool-second]').fill('a\nc');await page.locator('[data-tool-run]').click();await expect(page.locator('[data-tool-output]')).toHaveValue('  a\n- b\n+ c');
 await visit('regex-tester');await page.locator('[data-tool-input]').fill('hello 123');await page.locator('[data-tool-run]').click();await expect(page.locator('[data-tool-output]')).toContainText('',{useInnerText:false});await expect.poll(async()=>JSON.parse(await page.locator('[data-tool-output]').inputValue()).length).toBe(2);await page.locator('[data-tool-pattern]').fill('(a+)+$');await page.locator('[data-tool-input]').fill('a'.repeat(2000)+'!');await page.locator('[data-tool-run]').click();await expect(page.locator('[data-tool-status]')).toContainText('terminated');await expect(page.locator('[data-tool-run]')).toBeEnabled();
 for(const id of ['css-gradient','color-palette']){await visit(id);await page.locator('[data-tool-run]').click();expect((await page.locator('[data-tool-output]').inputValue()).length).toBeGreaterThan(20);for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}}
 expect(errors).toEqual([]);
});
