import {test,expect} from '@playwright/test';
test('approved homepage badge, headline and slogan localize and fit mobile/desktop',async({page})=>{
 await page.goto('/');await expect(page.locator('html')).toHaveClass(/js/);
 for(const [locale,badge,slogan,title]of [['tr','MERAK ALANI','Merakını harekete geçir.','BİR ŞEY OYNA.'],['en','SPACE FOR CURIOSITY','Put your curiosity into motion.','PLAY SOMETHING.']]){
  await page.locator(`[data-locale="${locale}"]`).click();await expect(page.locator('.hero [data-i18n="home.preview"]')).toHaveText(badge);await expect(page.locator('.hero [data-i18n="home.description"]')).toHaveText(slogan);expect((await page.locator('.hero h1 span').allTextContents()).join(' ')).toBe(title);
  for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const box=await page.locator('.hero .pill').boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width);}
 }
});
test('CREATE reset cancels safely, clears draft/result/share and preserves old shared payload and unrelated storage',async({page,browser})=>{
 await page.goto('/create/');await expect(page.locator('[data-creator]')).toHaveAttribute('data-ready','true');await page.evaluate(()=>localStorage.setItem('legacy-preserved','yes'));
 await page.locator('[data-creator-title]').fill('Fresh quiz');await page.locator('[data-question]').fill('Tea?');await page.locator('[data-option]').nth(0).fill('Yes');await page.locator('[data-option]').nth(1).fill('No');await page.locator('[data-creator-preview]').click();await page.locator('[data-creator-publish]').click();const link=await page.locator('[data-creator-link]').inputValue();
 await page.locator('[data-creator-reset]').click();await page.locator('[data-creator-reset-cancel]').click();await expect(page.locator('[data-creator-link]')).toHaveValue(link);await expect(page.locator('[data-creator-title]')).toHaveValue('Fresh quiz');
 await page.locator('[data-locale=tr]').click();await expect(page.locator('[data-creator-reset]')).toHaveText('YENİ OLUŞTUR');await page.locator('[data-creator-reset]').click();await page.locator('[data-creator-reset-yes]').click();await expect(page.locator('[data-creator-title]')).toHaveValue('');await expect(page.locator('[data-question]')).toHaveCount(1);await expect(page.locator('[data-option]').nth(0)).toHaveValue('');await expect(page.locator('[data-creator-link]')).toHaveValue('');await expect(page.locator('[data-creator-share]')).toBeHidden();await expect(page.locator('[data-creator-player]')).toBeEmpty();await expect(page.locator('[data-creator-title]')).toBeFocused();
 expect(await page.evaluate(()=>localStorage.getItem('katovia:v2:creator-draft'))).toBeNull();expect(await page.evaluate(()=>localStorage.getItem('legacy-preserved'))).toBe('yes');await page.reload();await expect(page.locator('[data-creator-title]')).toHaveValue('');
 const context=await browser.newContext();try{const friend=await context.newPage();await friend.goto(link.replace('https://katovia.com','http://127.0.0.1:4173'));await expect(friend.locator('[data-answer]')).toHaveCount(2);}finally{await context.close();}
});
test('CREATE reset stays usable with denied storage',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('denied');}}));await page.goto('/create/');await expect(page.locator('[data-creator]')).toHaveAttribute('data-ready','true');await page.locator('[data-creator-title]').fill('Draft');await page.locator('[data-creator-reset]').click();await page.locator('[data-creator-reset-yes]').click();await expect(page.locator('[data-creator-title]')).toHaveValue('');await expect(page.locator('[data-creator-status]')).toContainText('could not be removed');
});
test('Duel result card preserves score, target, link and manual sharing across locale changes and rematch',async({page},info)=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'share',{value:undefined});Object.defineProperty(navigator,'clipboard',{value:undefined});});await page.goto('/d/?id=v1.5000');await expect(page.locator('[data-duel]')).toHaveAttribute('data-ready','true');await page.locator('[data-duel-action]').click();await expect(page.locator('[data-duel-action]')).toHaveAttribute('data-state','signal',{timeout:6000});await page.locator('[data-duel-action]').click();await expect(page.locator('[data-duel-card]')).toBeVisible();const score=await page.locator('[data-duel-score]').innerText(),link=await page.locator('[data-duel-link]').inputValue();await expect(page.locator('[data-duel-result-target]')).toHaveText('Target: 5000 ms');
 await page.locator('[data-locale=tr]').click();expect((await page.locator('[data-duel-score]').innerText()).replaceAll('.','')).toBe(score.replaceAll(',',''));await expect(page.locator('[data-duel-link]')).toHaveValue(link);await page.locator('[data-duel-share]').click();await expect(page.locator('[data-duel-link]')).toBeFocused();
 for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.screenshot({path:info.outputPath('duel-card-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('duel-card-mobile.png'),fullPage:true});await page.locator('[data-duel-rematch]').click();await expect(page.locator('[data-duel-card]')).toBeHidden();await expect(page.locator('[data-duel-action]')).toHaveAttribute('data-state','ready');
});
test('Alphabet profile labels and SEO localize while query, selected symbol and search survive',async({page})=>{
 await page.goto('/tools/alphabet-lab/?profile=greek-modern&keep=1#greek-modern-03b2');await expect(page.locator('[data-tool]')).toHaveAttribute('data-ready','true');await page.locator('[data-alpha-search]').fill('Beta');const url=page.url();await page.locator('[data-locale=tr]').click();for(const [id,label]of [['greek-modern','Modern Yunanca'],['cyrillic-russian','Rus Kiril Alfabesi'],['morse-international','Uluslararası Mors Kodu']])await expect(page.locator(`[data-alpha-profile="${id}"]`)).toHaveText(label);expect(page.url()).toBe(url);await expect(page.locator('[data-alpha-search]')).toHaveValue('Beta');await expect(page.locator('[data-alpha-symbol][aria-pressed=true]')).toHaveCount(1);await expect(page.locator('meta[name=description]')).toHaveAttribute('content',/Yunanca.*Kiril.*Hiragana.*Mors.*Braille/);await page.locator('[data-locale=en]').click();await expect(page.locator('[data-alpha-profile=greek-modern]')).toHaveText('Modern Greek');expect(page.url()).toBe(url);
});
test('Three local explanatory illustrations have bilingual alt/captions, intrinsic dimensions and no external requests',async({page})=>{
 const external=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:4173'))external.push(r.url());});for(const slug of ['antikythera-mechanism','rongorongo-script','turin-shroud'])for(const locale of ['tr','en']){await page.goto((locale==='tr'?'/tr':'')+'/mysteries/'+slug+'/');const image=page.locator('.mystery-visual img');await expect(image).toHaveAttribute('width','800');await expect(image).toHaveAttribute('height','400');expect((await image.getAttribute('alt')).length).toBeGreaterThan(25);expect(await image.evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);await expect(page.locator('.mystery-visual figcaption')).toContainText(locale==='tr'?/Temsili/:/illustration/i);for(const width of [360,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}}expect(external).toEqual([]);
});
