import assert from 'node:assert/strict';
export async function qaBrand(page,base){
 const errors=[],external=[];const onError=e=>errors.push(e.message),onRequest=r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(base+'/'))external.push(r.url());};page.on('pageerror',onError);page.on('request',onRequest);
 try{
  assert.equal((await page.goto(base+'/')).status(),200);await page.waitForSelector('html.js');
  for(const [locale,badge,slogan,headline]of [['tr','MERAK ALANI','Merakını harekete geçir.','BİR ŞEY OYNA.'],['en','SPACE FOR CURIOSITY','Put your curiosity into motion.','PLAY SOMETHING.']]){
   await page.locator(`[data-locale="${locale}"]`).click();assert.equal(await page.locator('.hero [data-i18n="home.preview"]').innerText(),badge);assert.equal(await page.locator('.hero [data-i18n="home.description"]').innerText(),slogan);assert.equal((await page.locator('.hero h1 span').allTextContents()).join(' '),headline);
   for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  }
  for(const locale of ['tr','en']){
   await page.goto(base+'/create/');await page.waitForSelector('[data-creator][data-ready="true"]');await page.locator(`[data-locale="${locale}"]`).click();await page.locator('[data-creator-title]').fill('Brand QA');await page.locator('[data-question]').fill('Ready?');await page.locator('[data-option]').nth(0).fill('Yes');await page.locator('[data-option]').nth(1).fill('No');await page.locator('[data-creator-preview]').click();await page.locator('[data-creator-publish]').click();const link=await page.locator('[data-creator-link]').inputValue();assert.ok(link.startsWith('https://katovia.com/p/#'));
   await page.locator('[data-creator-reset]').click();await page.locator('[data-creator-reset-cancel]').click();assert.equal(await page.locator('[data-creator-link]').inputValue(),link);await page.locator('[data-creator-reset]').click();await page.locator('[data-creator-reset-yes]').click();assert.equal(await page.locator('[data-creator-title]').inputValue(),'');assert.equal(await page.locator('[data-question]').count(),1);assert.equal(await page.locator('[data-creator-link]').inputValue(),'');assert.ok(await page.locator('[data-creator-share]').isHidden());assert.equal(await page.evaluate(()=>localStorage.getItem('katovia:v2:creator-draft')),null);
   await page.goto(link.replace('https://katovia.com',base));await page.waitForSelector('[data-answer]');assert.equal(await page.locator('[data-answer]').count(),2);
  }
  await page.goto(base+'/d/?id=v1.5000');await page.waitForSelector('[data-duel][data-ready="true"]');await page.locator('[data-duel-action]').click();await page.waitForFunction(()=>document.querySelector('[data-duel-action]').dataset.state==='signal');await page.locator('[data-duel-action]').click();assert.ok(await page.locator('[data-duel-card]').isVisible());const link=await page.locator('[data-duel-link]').inputValue();assert.ok(/^https:\/\/katovia.com\/d\/\?id=v1\./.test(link));await page.locator('[data-locale=tr]').click();assert.equal(await page.locator('[data-duel-link]').inputValue(),link);await page.locator('[data-duel-share]').click();await page.waitForFunction(()=>!!window.__qaShare);assert.ok((await page.evaluate(()=>window.__qaShare)).includes(link));await page.locator('[data-duel-rematch]').click();assert.ok(await page.locator('[data-duel-card]').isHidden());
  await page.goto(base+'/tools/alphabet-lab/?profile=greek-modern&keep=1#greek-modern-03b2');await page.waitForSelector('[data-tool][data-ready="true"]');await page.locator('[data-alpha-search]').fill('Beta');const url=page.url();await page.locator('[data-locale=tr]').click();for(const [id,title]of [['greek-modern','Modern Yunanca'],['cyrillic-russian','Rus Kiril Alfabesi'],['morse-international','Uluslararası Mors Kodu']])assert.equal(await page.locator(`[data-alpha-profile="${id}"]`).innerText(),title);assert.equal(page.url(),url);assert.equal(await page.locator('[data-alpha-search]').inputValue(),'Beta');assert.equal(await page.locator('[data-alpha-symbol][aria-pressed=true]').count(),1);
  await page.goto(base+'/tools/');await page.waitForSelector('html.js');for(const locale of ['tr','en']){await page.locator(`[data-locale="${locale}"]`).click();const copy=await page.locator('.section-intro p').last().innerText();assert.ok(locale==='tr'?copy.includes('ücretsiz online araçlar'):copy.includes('Free online tools'));assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'),'https://katovia.com/tools/');}
  for(const id of ['antikythera-mechanism','rongorongo-script','turin-shroud'])for(const locale of ['tr','en']){await page.goto(base+(locale==='tr'?'/tr':'')+'/mysteries/'+id+'/');const image=page.locator('.mystery-visual img');assert.equal(await image.getAttribute('width'),'800');assert.equal(await image.getAttribute('height'),'400');assert.ok((await image.getAttribute('alt')).length>25);assert.ok(await image.evaluate(img=>img.complete&&img.naturalWidth>0));assert.equal(await page.locator('h1').count(),1);}
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('Brand/UI live QA passed: locked TR/EN hero, four widths, CREATE reset and old links, Duel score/share/rematch, Alphabet URL/search/profile state, TOOLS canonical/copy, six localized illustration pages and zero external runtime requests.');
 }finally{page.off('pageerror',onError);page.off('request',onRequest);}
}
