import {dataset,profiles,validateDataset} from './model.js';
import {translate} from '../../i18n/index.js';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=(key,tag='span',attrs='')=>`<${tag} data-i18n="${key}" ${attrs}>${escape(translate('en',key))}</${tag}>`;
const bilingual=(values,tag='span',attrs='')=>`<${tag} data-alpha-tr="${escape(values.tr)}" data-alpha-en="${escape(values.en)}" ${attrs}>${escape(values.en)}</${tag}>`;
const display=entry=>entry.pattern||entry.forms.map(form=>form.text).join(' / ');
export function alphabetMarkup(){
 validateDataset();
 return `<section class="activity-panel tool-panel alphabet-lab" data-tool="alphabet-lab">
 ${text('alphabet.intro','p')}<div class="alphabet-enhanced" hidden>
 <div class="alphabet-profile-choices" role="group" aria-label="Profiles" data-i18n-label="alphabet.profiles">${profiles.filter(profile=>profile.systemId!=='braille').map(profile=>bilingual(profile.title,'button',`type="button" class="button" data-alpha-profile="${profile.id}" aria-pressed="false"`)).join('')}${text('alphabet.braille','button','type="button" class="button" data-alpha-system="braille" aria-pressed="false"')}</div>
 <div data-alpha-braille-choices hidden><p>${text('alphabet.brailleChoose')}</p><div class="alphabet-profile-choices" role="group" aria-label="Braille profiles">${profiles.filter(profile=>profile.systemId==='braille').map(profile=>bilingual(profile.title,'button',`type="button" class="button" data-alpha-profile="${profile.id}" aria-pressed="false"`)).join('')}</div></div>
 <label class="alphabet-search">${text('alphabet.search')}<input type="search" data-alpha-search maxlength="100" autocomplete="off" spellcheck="false"></label><p data-alpha-count role="status" aria-live="polite"></p>
 <div class="alphabet-workspace"><div><div data-alpha-grid class="alphabet-grid"></div>${text('alphabet.empty','p','data-alpha-empty hidden')}</div><section class="alphabet-detail" data-alpha-detail tabindex="-1" aria-label="Symbol details" data-i18n-label="alphabet.details">${text('alphabet.choose','p')}</section></div>
 </div><div class="alphabet-reference" data-alpha-reference>
 ${text('alphabet.nojs','p')}<nav class="alphabet-reference-links" aria-label="Profiles">${profiles.map(profile=>`<a href="#ref-${profile.id}">${escape(profile.title.en)}</a>`).join('')}</nav>
 ${profiles.map(profile=>`<section id="ref-${profile.id}" data-alpha-static-profile="${profile.id}">${bilingual(profile.title,'h2')}<p>${profile.expectedCount} ${text('alphabet.records')}</p><div class="alphabet-table-scroll"><table><caption>${escape(profile.title.en)} — ${profile.expectedCount}</caption><thead><tr>${['glyph','name','romanization','reading','unicode','source'].map(key=>text('alphabet.'+key,'th','scope="col"')).join('')}</tr></thead><tbody>${profile.entries.map(entry=>`<tr id="${entry.id}" data-alpha-static-entry="${entry.id}"><th scope="row" lang="${profile.languageTag||'en'}">${escape(display(entry))}${entry.inputToken?` (${escape(entry.inputToken)})`:''}${entry.dots?`<span class="alphabet-dots-label">${text('alphabet.dots')}: ${entry.dots.join('-')}</span>`:''}</th><td>${bilingual(entry.symbolName)}</td><td>${entry.romanization?escape(entry.romanization.value)+'<small>'+escape(entry.romanization.scheme)+'</small>':text('alphabet.notApplicable')}</td><td>${bilingual(entry.pronunciation.text)}</td><td>${entry.forms.map(form=>escape(form.codePoints.join(' '))+'<small>'+escape(form.unicodeNames.join('; '))+'</small>').join('')}</td><td>${profile.sourceRefs.filter(id=>id!=='ucd').map(id=>{const source=dataset.sources.find(item=>item.id===id);return `<a href="${escape(source.url)}">${escape(source.title)}</a><small>${escape(source.version)}</small>`;}).join('')}</td></tr>`).join('')}</tbody></table></div></section>`).join('')}
 </div><details class="alphabet-provenance"><summary>${text('alphabet.sources')}</summary><p>${text('alphabet.dataset')}: ${dataset.datasetVersion} · Unicode ${dataset.unicodeVersion}</p>${dataset.sources.map(source=>`<p><a href="${escape(source.url)}">${escape(source.title)}</a><br>${escape(source.version)}<br><small>SHA-256: ${source.sha256}</small></p>`).join('')}</details>
 <details class="alphabet-provenance"><summary>Unicode License V3</summary><pre class="alphabet-license">${escape(dataset.license?.text||'Unicode License V3 — https://www.unicode.org/license.txt')}</pre></details>
 ${text('alphabet.boundaries','p','class="tool-hint"')}<p data-tool-status role="status" aria-live="polite"></p></section>`;
}
