import {validateQuiz,encodeQuiz,decodeQuiz} from './model.js';
import {playQuiz} from './player.js';
import {storage} from '../core/storage.js';
import {shareText} from '../core/share.js';
import {i18n,t} from '../i18n/index.js';
import {track,trackShareOutcome} from '../core/analytics.js';
import '../styles/creator.css';
export function mount(root){let playerDispose,dead=false,link='';const listeners=[];const listen=(node,event,fn)=>{node.addEventListener(event,fn);listeners.push(()=>node.removeEventListener(event,fn));};const get=name=>root.querySelector(`[data-creator-${name}]`);const status=get('status')||root.querySelector('[data-creation-status]');
 function setStatus(key){if(key){status.dataset.i18n=key;status.textContent=t(key);}else{delete status.dataset.i18n;status.textContent='';}}
 if(root.hasAttribute('data-creation')){const load=()=>{playerDispose?.();playerDispose=null;try{const quiz=decodeQuiz(location.hash.slice(1));playerDispose=playQuiz(get('player'),quiz);setStatus(null);track('creation_opened',{template_id:'know_me'});}catch{setStatus('creator.invalid');}};listen(window,'hashchange',load);const localeUnsubscribe=i18n.subscribe(()=>{if(!playerDispose)setStatus('creator.invalid');});load();root.dataset.ready='true';return {dispose(){dead=true;localeUnsubscribe();playerDispose?.();listeners.forEach(fn=>fn());}};}
 let quiz;try{quiz=validateQuiz(storage.get('creator-draft'),{draft:true});}catch{quiz={version:1,title:'',contentLocale:i18n.locale,theme:'lime',questions:[{text:'',options:['',''],correct:0}]};}
 const form=root.querySelector('form'),questions=get('questions'),title=get('title'),locale=get('locale'),theme=get('theme');title.value=quiz.title;locale.value=quiz.contentLocale;theme.value=quiz.theme;
 function read(){quiz.title=title.value;quiz.contentLocale=locale.value;quiz.theme=theme.value;questions.querySelectorAll('fieldset').forEach((field,index)=>{quiz.questions[index]={text:field.querySelector('[data-question]').value,options:[...field.querySelectorAll('[data-option]')].map(x=>x.value),correct:Number(field.querySelector('select').value)};});return quiz;}
 function invalidate(){get('link').value='';get('share').hidden=true;link='';setStatus(storage.set('creator-draft',validateQuiz(read(),{draft:true}))?'creator.saved':'creator.unsaved');playerDispose?.();playerDispose=null;}
 function renderQuestions(){questions.replaceChildren();quiz.questions.forEach((question,index)=>{const field=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=t('creator.question',{number:index+1});field.append(legend);const label=(text,max,value,attr)=>{const node=document.createElement('label');node.textContent=text;const input=document.createElement('input');input.maxLength=max;input.required=true;input.value=value;input.setAttribute(attr,'');node.append(input);field.append(node);};label(t('creator.questionText'),120,question.text,'data-question');question.options.forEach((value,i)=>label(t('creator.option',{number:i+1}),60,value,'data-option'));const correctLabel=document.createElement('label');correctLabel.textContent=t('creator.correct');const correct=document.createElement('select');question.options.forEach((_,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=String(i+1);correct.append(option);});correct.value=String(question.correct);correctLabel.append(correct);field.append(correctLabel);const remove=document.createElement('button');remove.type='button';remove.className='button';remove.textContent=t('creator.remove');remove.disabled=quiz.questions.length===1;remove.onclick=()=>{read();quiz.questions.splice(index,1);renderQuestions();invalidate();};field.append(remove);questions.append(field);});get('add').disabled=quiz.questions.length>=8;}
 renderQuestions();listen(form,'input',invalidate);listen(form,'change',invalidate);listen(get('add'),'click',()=>{read();if(quiz.questions.length>=8)return;quiz.questions.push({text:'',options:['',''],correct:0});renderQuestions();invalidate();});listen(form,'submit',event=>{event.preventDefault();try{const clean=validateQuiz(read());playerDispose?.();playerDispose=playQuiz(get('player'),clean);setStatus('creator.previewing');}catch{setStatus('creator.error');}});
 listen(get('publish'),'click',()=>{if(!form.reportValidity())return;try{const clean=validateQuiz(read());link='https://katovia.com/p/#'+encodeQuiz(clean);get('link').value=link;get('share').hidden=false;setStatus('creator.linkReady');track('creator_published',{template_id:'know_me'});}catch(error){setStatus(error instanceof RangeError?'creator.tooLong':'creator.error');}});
 listen(get('share'),'click',async()=>{if(!link)return;track('share_opened');const result=await shareText({title:'Katovia',text:quiz.title,url:link});if(dead)return;trackShareOutcome(result);if(result.status==='manual'){get('link').focus();get('link').select();}setStatus(result.status==='cancelled'?'creator.cancelled':result.status==='manual'?'tool.manual':result.status==='copied'?'tool.copied':'creator.handoff');});
 const unsubscribe=i18n.subscribe(()=>{read();renderQuestions();});track('creator_started',{template_id:'know_me'});root.dataset.ready='true';return {dispose(){dead=true;unsubscribe();playerDispose?.();listeners.forEach(fn=>fn());}};
}
