export const imageLimits=Object.freeze({bytes:12*1024*1024,pixels:16000000,edge:8192,outputEdge:2048});
const fail=key=>{throw new Error(key);};
const checkSize=(w,h)=>{if(w>imageLimits.edge||h>imageLimits.edge||w*h>imageLimits.pixels)fail('image.pixelLimit');};
export function inspectImage(buffer){const a=new Uint8Array(buffer),d=new DataView(buffer);let width,height,type;
 const ascii=(start,n)=>String.fromCharCode(...a.slice(start,start+n));
 if(a.length>=33&&a[0]===137&&ascii(1,3)==='PNG'&&a[4]===13&&a[5]===10&&a[6]===26&&a[7]===10){if(ascii(12,4)!=='IHDR'||d.getUint32(8)!==13)fail('image.invalid');width=d.getUint32(16);height=d.getUint32(20);type='image/png';for(let p=8;p+12<=a.length;){const size=d.getUint32(p),kind=ascii(p+4,4);if(kind==='acTL')fail('image.animated');if(size>a.length-p-12)fail('image.invalid');p+=size+12;if(kind==='IEND')break;}}
 else if(a.length>=12&&a[0]===255&&a[1]===216){type='image/jpeg';let p=2;while(p+4<=a.length){if(a[p++]!==255)fail('image.invalid');while(a[p]===255)p++;const marker=a[p++];if(marker===217||marker===218)break;if(marker===1||marker>=208&&marker<=215)continue;const size=d.getUint16(p);if(size<2||p+size>a.length)fail('image.invalid');if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){if(size<7)fail('image.invalid');height=d.getUint16(p+3);width=d.getUint16(p+5);break;}p+=size;}}
 else if(a.length>=20&&ascii(0,4)==='RIFF'&&ascii(8,4)==='WEBP'){type='image/webp';if(d.getUint32(4,true)+8>a.length)fail('image.invalid');for(let p=12;p+8<=a.length;){const kind=ascii(p,4),size=d.getUint32(p+4,true),q=p+8;if(size>a.length-q)fail('image.invalid');if(kind==='ANIM'||kind==='ANMF')fail('image.animated');if(kind==='VP8X'&&size>=10){if(a[q]&2)fail('image.animated');width=1+a[q+4]+(a[q+5]<<8)+(a[q+6]<<16);height=1+a[q+7]+(a[q+8]<<8)+(a[q+9]<<16);}else if(kind==='VP8 '&&size>=10&&a[q+3]===157&&a[q+4]===1&&a[q+5]===42){width=d.getUint16(q+6,true)&16383;height=d.getUint16(q+8,true)&16383;}else if(kind==='VP8L'&&size>=5&&a[q]===47){const bits=d.getUint32(q+1,true);width=(bits&16383)+1;height=((bits>>>14)&16383)+1;}if(width&&height)checkSize(width,height);p=q+size+(size%2);}}
 else fail('image.invalid');
 if(!width||!height)fail('image.invalid');checkSize(width,height);return {width,height,type};
}
export function fitImage(width,height,maxWidth,maxHeight){if(!Number.isFinite(maxWidth)||!Number.isFinite(maxHeight)||maxWidth<1||maxHeight<1||maxWidth>imageLimits.outputEdge||maxHeight>imageLimits.outputEdge)fail('image.resizeLimit');const ratio=Math.min(1,maxWidth/width,maxHeight/height);return {width:Math.max(1,Math.round(width*ratio)),height:Math.max(1,Math.round(height*ratio))};}
