import {translate} from '../i18n/index.js';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=(key,tag='span',attrs='')=>`<${tag} data-i18n="${key}" ${attrs}>${escape(translate('en',key))}</${tag}>`;
const button=(key,attr)=>text(key,'button',`class="button" type="button" ${attr}`);
const panel=(id,content)=>`<section class="activity-panel tool-panel" data-tool="${id}">${text('newTool.local','p','class="local-badge"')}${content}<p data-tool-status role="status" aria-live="polite"></p></section>`;
export function newToolMarkup(id){
 if(id==='image-compressor')return panel(id,`<div class="image-drop" data-image-drop><label>${text('image.choose')}<input data-image-file type="file" accept="image/jpeg,image/png,image/webp"></label>${text('image.drop','p','class="tool-hint"')}</div>${text('image.limits','p','class="tool-hint"')}<p data-image-info class="tool-info"></p><div class="tool-row"><label>${text('image.format')}<select data-image-format><option value="image/webp">WebP</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></label><label>${text('image.quality')} <output data-image-quality-value>80%</output><input data-image-quality type="range" min="0.1" max="1" step="0.05" value="0.8"></label></div><p data-image-quality-note hidden class="tool-hint" data-i18n="image.pngNote">${escape(translate('en','image.pngNote'))}</p><p data-image-jpeg-note hidden class="tool-hint" data-i18n="image.jpegNote">${escape(translate('en','image.jpegNote'))}</p><div class="tool-row"><label>${text('image.maxWidth')}<input data-image-width type="number" min="1" max="2048" value="1600"></label><label>${text('image.maxHeight')}<input data-image-height type="number" min="1" max="2048" value="1600"></label></div>${button('image.compress','data-image-run disabled')}<img class="image-output" data-image-preview hidden data-i18n-label="image.preview" aria-label="Compressed preview" alt="${escape(translate('en','image.preview'))}"><p data-image-result class="tool-info"></p>${text('image.download','a','class="button button-accent" data-image-download hidden download')}`);
 if(id==='lucky-draw')return panel(id,`<label>${text('lucky.listLabel')}<textarea data-lucky-input rows="6" maxlength="16000" spellcheck="false"></textarea></label>${text('lucky.limits','p','class="tool-hint"')}<p data-lucky-count></p><ol class="lucky-list" data-lucky-list></ol>${button('lucky.pick','data-lucky-pick disabled')}<div class="lucky-winner" data-lucky-winner role="status" aria-live="polite"></div><div class="tool-row">${button('lucky.remove','data-lucky-remove disabled')}${button('lucky.copy','data-lucky-copy disabled')}${button('lucky.reset','data-lucky-reset')}</div><textarea data-lucky-manual hidden readonly data-i18n-label="share.textLabel" aria-label="Share text"></textarea>${text('lucky.storageNote','p','class="tool-hint"')}`);
 if(id==='pixel-art-grid')return panel(id,`<div class="tool-row"><label>${text('pixel.size')}<select data-pixel-size><option value="8">8 × 8</option><option value="16" selected>16 × 16</option><option value="32">32 × 32</option></select></label><label>${text('pixel.color')}<input data-pixel-color type="color" value="#cdfc7b"></label></div><div class="tool-row pixel-modes" role="group" data-i18n-label="pixel.modes" aria-label="Drawing tools">${['pencil','eraser','fill'].map(mode=>button('pixel.'+mode,`data-pixel-mode="${mode}" aria-pressed="${mode==='pencil'}"`)).join('')}</div><div class="pixel-swatches">${['#cdfc7b','#53c7c0','#8188ed','#f694b3','#ffffff','#101a18'].map(hex=>`<button type="button" data-pixel-swatch="${hex}" aria-label="${hex}"><i aria-hidden="true" style="--swatch:${hex}"></i>${hex.toUpperCase()}</button>`).join('')}</div><label class="tool-check"><input data-pixel-lines type="checkbox" checked>${text('pixel.lines')}</label><canvas data-pixel-canvas class="pixel-canvas" tabindex="0" role="application" data-i18n-label="pixel.canvasLabel" aria-label="${escape(translate('en','pixel.canvasLabel'))}" aria-describedby="pixel-help"></canvas><p id="pixel-help" class="tool-hint" data-i18n="pixel.instructions">${escape(translate('en','pixel.instructions'))}</p><p data-pixel-cursor aria-live="polite"></p><div class="tool-row">${button('pixel.undo','data-pixel-undo disabled')}${button('pixel.redo','data-pixel-redo disabled')}${button('pixel.clear','data-pixel-clear')}${button('pixel.export','data-pixel-export')}</div>${text('pixel.download','a','class="button button-accent" data-pixel-download hidden download')}${text('pixel.exportNote','p','class="tool-hint"')}`);
 return null;
}
